/**
 * create_firebase_project.js
 * Tự động tạo Firebase project qua Firebase REST API
 * Chạy: node create_firebase_project.js
 * 
 * Lưu ý: Script này yêu cầu bạn đã đăng nhập Firebase CLI
 * Nếu chưa: npx firebase-tools login
 */

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const PROJECT_ID = 'vku-room-booking-17t';
const FIREBASE_CONFIG_PATH = path.join(__dirname, 'src', 'services', 'firebaseConfig.ts');

function run(cmd, opts = {}) {
  try {
    return execSync(cmd, { encoding: 'utf8', stdio: opts.silent ? 'pipe' : 'inherit', ...opts });
  } catch (e) {
    return null;
  }
}

async function main() {
  console.log('🔥 VKU Room Booking — Firebase Auto Setup\n');

  // 1. Check firebase CLI
  const fbVersion = run('npx firebase-tools --version', { silent: true });
  if (!fbVersion) {
    console.log('📦 Cài Firebase CLI...');
    run('npm install -g firebase-tools');
  } else {
    console.log(`✓ Firebase CLI: ${fbVersion.trim()}`);
  }

  // 2. Check login
  const user = run('npx firebase-tools login:list', { silent: true });
  if (!user || !user.includes('@')) {
    console.log('\n⚠️  Bạn chưa đăng nhập Firebase. Đang mở trình duyệt...');
    run('npx firebase-tools login');
  }

  // 3. Tạo project (ignore error nếu đã tồn tại)
  console.log(`\n📁 Tạo Firebase project "${PROJECT_ID}"...`);
  run(`npx firebase-tools projects:create ${PROJECT_ID} --display-name "VKU Room Booking" 2>/dev/null`, { silent: true });

  // 4. Lấy config qua firebase CLI
  console.log('\n🔑 Lấy Web App config...');
  
  // Tạo web app nếu chưa có
  run(`npx firebase-tools apps:create WEB "VKU Room Booking Web" --project ${PROJECT_ID}`, { silent: true });
  
  // Lấy SDK config
  const configRaw = run(
    `npx firebase-tools apps:sdkconfig WEB --project ${PROJECT_ID}`,
    { silent: true }
  );

  if (!configRaw) {
    // Fallback: output hướng dẫn thủ công
    console.log(`
❌ Không thể tự động lấy config. Vui lòng thực hiện thủ công:

1. Vào https://console.firebase.google.com/project/${PROJECT_ID}/settings/general
2. Scroll xuống "Your apps" → Click "</>" → Register app
3. Copy firebaseConfig object
4. Mở file: src/services/firebaseConfig.ts
5. Thay thế đoạn config trong file

Sau đó tiếp tục deploy bình thường.
`);
    return;
  }

  // 5. Parse config từ output
  const apiKeyMatch = configRaw.match(/apiKey:\s*["']([^"']+)["']/);
  const authDomainMatch = configRaw.match(/authDomain:\s*["']([^"']+)["']/);
  const projectIdMatch = configRaw.match(/projectId:\s*["']([^"']+)["']/);
  const storageBucketMatch = configRaw.match(/storageBucket:\s*["']([^"']+)["']/);
  const messagingSenderIdMatch = configRaw.match(/messagingSenderId:\s*["']([^"']+)["']/);
  const appIdMatch = configRaw.match(/appId:\s*["']([^"']+)["']/);

  if (!apiKeyMatch || !appIdMatch) {
    console.log('❌ Không parse được config. Output:\n', configRaw.substring(0, 500));
    return;
  }

  const firebaseConfig = {
    apiKey: apiKeyMatch[1],
    authDomain: authDomainMatch?.[1] || `${PROJECT_ID}.firebaseapp.com`,
    projectId: projectIdMatch?.[1] || PROJECT_ID,
    storageBucket: storageBucketMatch?.[1] || `${PROJECT_ID}.appspot.com`,
    messagingSenderId: messagingSenderIdMatch?.[1] || '',
    appId: appIdMatch[1],
  };

  // 6. Ghi vào firebaseConfig.ts
  const configFileContent = `// Firebase configuration for VKU Room Booking App
// Auto-generated by create_firebase_project.js on ${new Date().toISOString()}
import { initializeApp, getApps, FirebaseApp } from 'firebase/app';
import { getFirestore, Firestore } from 'firebase/firestore';

const firebaseConfig = {
  apiKey: "${firebaseConfig.apiKey}",
  authDomain: "${firebaseConfig.authDomain}",
  projectId: "${firebaseConfig.projectId}",
  storageBucket: "${firebaseConfig.storageBucket}",
  messagingSenderId: "${firebaseConfig.messagingSenderId}",
  appId: "${firebaseConfig.appId}",
};

let app: FirebaseApp;
let db: Firestore;

if (getApps().length === 0) {
  app = initializeApp(firebaseConfig);
} else {
  app = getApps()[0];
}

db = getFirestore(app);

export { db };
export default app;
`;

  fs.writeFileSync(FIREBASE_CONFIG_PATH, configFileContent, 'utf8');
  console.log(`\n✅ Đã ghi config vào: ${FIREBASE_CONFIG_PATH}`);

  // 7. Enable Firestore
  console.log('\n🗄️  Kích hoạt Cloud Firestore...');
  run(`npx firebase-tools firestore:databases:create --project ${PROJECT_ID} --location asia-southeast1`, { silent: true });

  // 8. Set Firestore rules (test mode - 30 days)
  const rulesContent = `rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if true; // Test mode - VKU Room Booking Demo
    }
  }
}`;
  fs.writeFileSync('firestore.rules', rulesContent, 'utf8');
  run(`npx firebase-tools deploy --only firestore:rules --project ${PROJECT_ID}`, { silent: true });

  console.log(`
✅ Firebase setup hoàn tất!
   Project ID: ${PROJECT_ID}
   Firestore: Enabled (Asia Southeast 1 - Singapore)
   Rules: Test mode (read/write cho tất cả)

📋 Bước tiếp theo:
   1. node create_firebase_project.js đã chạy xong
   2. Bây giờ chạy: npx expo export -p web
   3. Sau đó: npx wrangler pages deploy dist --project-name vku-room-booking --branch master
`);
}

main().catch(console.error);
